spring:
  application:
    name: be-session

  datasource:
    url: jdbc:mysql://localhost:3306/likelion?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

cors:
  allowed-origins: http://localhost:3000, http://localhost:5173

jwt:
  secret: RWmnYnqBX93r0Ymzv2MziSt0mBAxaCURuLqZ49HBDuq
  access-token-expiration: 1800000

logging:
  level:
    root: INFO
    com.likelion.besession: DEBUG